version: '2.4'

services:
  ocrmypdf-watchdog:
    container_name: ocrmypdf-watchdog
    build: .
    #image: jxsl13/ocrmypdf-watchdog
    environment: 
      NUM_WORKRS: 3
      OCRMYPDF_ARGS: --pdf-renderer sandwich --tesseract-timeout 1800 --rotate-pages -l eng+fra+deu --deskew --clean --skip-text
    volumes: 
      - ./volumes/in:/in
      - ./volumes/out:/out
    network_mode: none
    mem_limit: 1024m     # limit RAM usage
    cpu_percent: 50     # limit CPU usage
    restart: unless-stopped